### ISSUE TITLE
Add Multiple Friends to Expense in New Expense Modal

### ISSUE THREAD

**Issue by brynbeaudry** [SplitSet3R/Split#87]
Can currently add only one friend to expense in expense modal.

@itsmattli  @nikoootine 
Is it possible to shared between < 2 People?

If so, I'll fix the controller and automatically update the owed expense as: 
the actual expense divided by the amount of friends sharing it.

**Comment by brynbeaudry** [comment]
I just checked and it isn't lol

In there future I guess there should just be a max.

**Comment by nikoootine** [comment]
We can add multiple friends into an expense. it's just a matter of adding more rows to the shared expenses with the same foreign expense key.

The front end right now just can't add more than one friend to an expense
