### ISSUE TITLE
"Shared With" Expense Column

### ISSUE THREAD

**Issue by brynbeaudry** [SplitSet3R/Split#88]
When User A shares expense with User B

The shared with column accurately says Shared with: User B

But when User B Logs in to see the same expense on their dashboard, its says it is Shared with User B

It should say shared with User A

**Comment by nikoootine** [comment]
We already have this column in our shared expenses table. It's called secondary_username

**Comment by brynbeaudry** [comment]
ahh, I get it now. The secondary user owes.
