### ISSUE TITLE
[FE] Make top section same length for pages

### ISSUE THREAD

**Issue by itsmattli** [SplitSet3R/Split#89]

**Comment by danielcapacio** [comment]
Fixed on branch fe-refactoring. Going to close once merged with staging
![alignment-fixed](https://cloud.githubusercontent.com/assets/15661260/24990846/b03a1176-1fcb-11e7-9680-96e97a7e2573.png)

**Comment by danielcapacio** [comment]
might need some testing on different screens, resolutions - but should be good
